// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sindice.linker.domain;

import com.sindice.linker.domain.Role;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect RoleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RoleDataOnDemand: @Component;
    
    private Random RoleDataOnDemand.rnd = new SecureRandom();
    
    private List<Role> RoleDataOnDemand.data;
    
    public Role RoleDataOnDemand.getNewTransientRole(int index) {
        Role obj = new Role();
        setRoleDescription(obj, index);
        setRoleName(obj, index);
        return obj;
    }
    
    public void RoleDataOnDemand.setRoleDescription(Role obj, int index) {
        String roleDescription = "roleDescription_" + index;
        if (roleDescription.length() > 200) {
            roleDescription = roleDescription.substring(0, 200);
        }
        obj.setRoleDescription(roleDescription);
    }
    
    public void RoleDataOnDemand.setRoleName(Role obj, int index) {
        String roleName = "roleName_" + index;
        obj.setRoleName(roleName);
    }
    
    public Role RoleDataOnDemand.getSpecificRole(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Role obj = data.get(index);
        return Role.findRole(obj.getId());
    }
    
    public Role RoleDataOnDemand.getRandomRole() {
        init();
        Role obj = data.get(rnd.nextInt(data.size()));
        return Role.findRole(obj.getId());
    }
    
    public boolean RoleDataOnDemand.modifyRole(Role obj) {
        return false;
    }
    
    public void RoleDataOnDemand.init() {
        data = Role.findRoleEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Role' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.sindice.linker.domain.Role>();
        for (int i = 0; i < 10; i++) {
            Role obj = getNewTransientRole(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
